services:
  postgres:
    image: postgres:15
    container_name: postgres_15
    environment:
      POSTGRES_DB: link_shortener
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: As0X!dP@ssw0rd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: